# Generated by Django 4.1.1 on 2022-09-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("sur_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
            ],
        ),
    ]
